# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15cAsIm2j6Q6PeZjzxg2sWut9xDSLHJpS
"""

import gradio as gr
import pandas as pd
import numpy as np
import joblib

# تحميل الموديل
model = joblib.load("xgb_credit_model.pkl")

def predict_fraud(country, ttype, amount, time):
    # input للموديل
    input_data = pd.DataFrame([[time, amount] + [0]*28], columns=model.get_booster().feature_names)

    # predict
    pred = model.predict(input_data)[0]
    prob = float(model.predict_proba(input_data)[0][1]) if hasattr(model, "predict_proba") else (1.0 if pred==1 else 0.0)

    # جدول HTML منسق مع ألوان حسب الاحتيال
    if prob < 0.3:
        row_color = "#d4edda"  # أخضر فاتح
    elif prob < 0.7:
        row_color = "#fff3cd"  # برتقالي فاتح
    else:
        row_color = "#f8d7da"  # أحمر فاتح

    table_html = f"""
    <table style="width:60%; border-collapse: collapse; margin-bottom:10px;">
      <tr style="background-color:#f2f2f2;">
        <th style="border:1px solid #ddd; padding:8px;">Feature</th>
        <th style="border:1px solid #ddd; padding:8px;">Value</th>
      </tr>
      <tr style="background-color:{row_color};">
        <td style="border:1px solid #ddd; padding:8px;">Country</td>
        <td style="border:1px solid #ddd; padding:8px;">{country}</td>
      </tr>
      <tr style="background-color:{row_color};">
        <td style="border:1px solid #ddd; padding:8px;">Type Transaction</td>
        <td style="border:1px solid #ddd; padding:8px;">{ttype}</td>
      </tr>
      <tr style="background-color:{row_color};">
        <td style="border:1px solid #ddd; padding:8px;">Amount</td>
        <td style="border:1px solid #ddd; padding:8px;">{amount}</td>
      </tr>
      <tr style="background-color:{row_color};">
        <td style="border:1px solid #ddd; padding:8px;">Time</td>
        <td style="border:1px solid #ddd; padding:8px;">{time}</td>
      </tr>
    </table>
    """

    # شريط probability gradient ديناميكي
    meter_html = f"""
    <label for="fraudMeter">Fraud Probability:</label>
    <div style="background:#eee; width:50%; height:30px; border-radius:5px; overflow:hidden;">
        <div style="width:{prob*100}%; height:100%; background:linear-gradient(to right, green, orange, red);"></div>
    </div>
    <span style="margin-left:10px; font-weight:bold;">{prob*100:.2f}%</span>
    <br><br>
    """

    # 6 if logic واقعية
    if amount > 5000 and time < 1000:
        msg = "<p style='color:red'>🚨 عملية كبيرة جدًا في وقت غير معتاد!</p>"
    elif amount > 3000 and time < 2000:
        msg = "<p style='color:orange'>⚠️ عملية كبيرة في وقت مبكر من اليوم.</p>"
    elif amount > 1000 and time > 80000:
        msg = "<p style='color:orange'>⚠️ عملية كبيرة في وقت متأخر من اليوم.</p>"
    elif amount < 50 and time > 80000:
        msg = "<p style='color:green'>✅ عملية صغيرة في وقت متأخر، تبدو طبيعية.</p>"
    elif amount < 500 and time < 5000:
        msg = "<p style='color:green'>✅ عملية صغيرة في وقت مبكر، تبدو طبيعية.</p>"
    elif amount > 2000 and 20000 < time < 60000:
        msg = "<p style='color:orange'>⚠️ عملية كبيرة خلال فترة نشطة من اليوم.</p>"
    else:
        msg = "<p style='color:blue'>ℹ️ لم يتم رصد سلوك غير طبيعي بشكل واضح.</p>"

    # if لكل Country
    if country == "Other" and prob > 0.6:
        msg += "<p style='color:red'>❌ العملية من دولة غير معتادة واحتمالية احتيال مرتفعة.</p>"
    elif country == "UK" and amount > 3000:
        msg += "<p style='color:orange'>⚠️ عملية كبيرة من المملكة المتحدة.</p>"
    elif country == "US" and amount < 50:
        msg += "<p style='color:green'>✅ عملية صغيرة داخل الولايات المتحدة تبدو آمنة.</p>"

    # if لكل Type Transaction
    if ttype == "Online" and amount > 3000:
        msg += "<p style='color:red'>⚠️ عملية أونلاين كبيرة.</p>"
    elif ttype == "Credit" and amount > 1000:
        msg += "<p style='color:orange'>⚠️ عملية ائتمانية كبيرة.</p>"
    elif ttype == "Offline" and amount < 100:
        msg += "<p style='color:green'>✅ عملية صغيرة أوفلاين تبدو طبيعية.</p>"

    # Mockup لأهم Features (تفسير)
    top_features = ["V1","V2","V3","Amount","Time"]
    shap_html = "<p><b>Top influencing features:</b> " + ", ".join(top_features) + "</p>"

    output_html = table_html + meter_html + msg + shap_html
    return output_html

iface = gr.Interface(
    fn=predict_fraud,
    inputs=[
        gr.Dropdown(["US","UK","Other"], label="Country"),
        gr.Dropdown(["Online","Credit","Offline"], label="Type Transaction"),
        gr.Slider(0,10000, step=10, label="Amount"),
        gr.Slider(0,86400, step=1, label="Time")
    ],
    outputs=gr.HTML(),
    title="Credit Card Fraud Detection",
    description="ادخل بيانات العملية وسيظهر Fraud / Not Fraud مع الاحتمالية."
)

iface.launch()